//
//  File.swift
//  
//
//  Created by Stefan Urbanek on 19/09/2023.
//
import PoieticCore

// TODO: Consolidate all the variable/reference types, we have way too many of them


/// Object describing a simulation state variable.
///
/// This is the core detail information of the simulation. There is one
/// state variable for each object, usually a node, that represent a state
/// in the simulation. A stock, a flow or an auxiliary - they all are state
/// variables.
///
public struct ComputedObject: CustomStringConvertible {
    /// ID of the object, usually a node, that represents the variable.
    public let id: ObjectID
    
    /// Index of the variable in the simulation state vector.
    ///
    public let variableIndex: Int
    
    /// Type of the variable value.
    ///
    public var valueType: ValueType
    
    /// Type denoting how the object is being computed.
    ///
    public let computation: ComputationalRepresentation
    
    /// Name of the variable.
    ///
    public let name: String
    
    public var description: String {
        "var(\(name), id:\(id), idx:\(variableIndex))"
    }
}

/// Type of the simulation variable.
///
/// - SeeAlso: ``SimulationVariable``
///
public enum SimulationVariableType: String {
    /// The simulation variable represents a computation defined
    /// by a node.
    case computed
    /// The simulation variable represents a built-in variable.
    ///
    case builtin
}

/// Reference to a variable.
///
/// The variable reference is used in arithmetic expressions and might represent
/// a built-in variable provided by the application or a value of an object.
///
/// One object can represent only one variable.
///
public enum StateVariableContent: Hashable, CustomStringConvertible {
    /// The variable is represented by an object with given object ID.
    ///
    case object(ObjectID)
    // TODO: point to computed object
    
    /// The variable is a built-in variable.
    ///
    case builtin(BuiltinVariable)
    
    // FIXME: Add Stateful function state.
    // case state(Int)
    
    public static func ==(lhs: StateVariableContent, rhs: StateVariableContent) -> Bool {
        switch (lhs, rhs) {
        case let (.object(left), .object(right)): return left == right
        case let (.builtin(left), .builtin(right)): return left == right
        default: return false
        }
    }

    public var description: String {
        switch self {
        case .object(let id): "object(\(id))"
        case .builtin(let variable): "builtin(\(variable))"
        }
    }
}

/// Structure representing a reference to a simulation variable.
///
/// The structure is analogous to an entry in a symbol table generated by the
/// compiler. It provides information about where a particular simulation
/// variable can be found in the simulation state.
///
/// This structure provides information about a variable used in the simulation.
/// Variable can be built-in or computed. The computed variable is representing
/// a node in the model, typically a node with a formula.
///
public struct StateVariable: CustomStringConvertible, TypedValue {
    // TODO: Rename to SimulationVariable
    // FIXME: Add name

    /// Index of the variable's value in a simulation state.
    ///
    public let index: Int

    /// Content of the state variable - whether it is an object or a builtin.
    ///
    public let content: StateVariableContent

    /// Type of the simulation variable.
    ///
    public var type: SimulationVariableType {
        switch content {
        case .builtin: .builtin
            // FIXME: Rename computed to object
        case .object: .computed
        }
    }

    
    /// Variable value type
    ///
    public let valueType: ValueType

    public let name: String
    
    /// ID of a simulation node that the variable represents, if the variable
    /// represents a node.
    ///
    /// ID is `nil` when the variable is a built-in variable.
    ///
    public var objectID: ObjectID? {
        switch content {
        case .builtin(_): nil
        case .object(let id): id
        }
    }

    public var description: String {
        "\(name)@\(index):\(type):\(valueType)"
    }
}

